from mongoengine import *


class Admin(Document):
    """
        Template for an admin account in the Database.
    """
    meta = {'db_alias': 'user',
            'collection': 'admin'}
    # has to be unique. enforced upon creation
    username = StringField(required=True)
    # saved as a hash generated by werzeug's generate_password_hash()
    password = StringField(required=True)
